In [15]:
%matplotlib notebook
import pandas

crime_places = pandas.read_csv('generated/crime_places_presence.csv', encoding='utf-8')
crime_places.drop(['Unnamed: 0'], axis=1, inplace=True)
crime_places.head()

,lng,lat,date,customdate,time,crime,barangay,city,modus,Bank,...,Reservior,Residential Building,Resort,Restaurant,River,Road,School,Sports Center,Tourist Attraction,Transport Terminal
0,125.808,7.44808,30/07/2017,"Sun - Jul 30, 2017",16:11:00,Vehicular Traffic Accident,Magugpo Poblacion,Tagum City,Not Indicated,160.0,...,NaN,NaN,NaN,150.0,NaN,NaN,NaN,NaN,NaN,NaN
1,125.803,7.44675,30/07/2017,"Sun - Jul 30, 2017",0:20:00,MURDER,Magugpo Poblacion,Tagum City,Stabbing/Hacking,120.0,...,NaN,NaN,NaN,70.0,NaN,NaN,100.0,NaN,NaN,NaN
2,125.803,7.44897,30/07/2017,"Sun - Jul 30, 2017",0:20:00,PHYSICAL INJURIES,Magugpo Poblacion,Tagum City,Stabbing/Hacking,120.0,...,NaN,NaN,NaN,130.0,NaN,NaN,60.0,NaN,90.0,NaN
3,125.818,7.45982,30/07/2017,"Sun - Jul 30, 2017",20:50:00,MURDER,Magugpo North,Tagum City,Shooting,NaN,...,NaN,NaN,NaN,160.0,NaN,NaN,180.0,NaN,NaN,NaN
4,125.818,7.46016,30/07/2017,"Sun - Jul 30, 2017",20:50:00,PHYSICAL INJURIES,Magugpo North,Tagum City,Shooting,NaN,...,NaN,NaN,NaN,160.0,NaN,NaN,160.0,NaN,NaN,NaN

In [16]:
import matplotlib as mpl

'nbAgg'